In [ ]:
import pandas as pd 
import numpy as np 
import matplotlib as mlp 
import seaborn as sns

In [2]:
df = pd.read_csv('churn.csv')
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [21]:
df['Exited'].value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

# data types 
1. row number is unique value 
2. CustomerId is also unique value 
3. surname is also the unique value 
4. credit score is numerical continious value 
5. geograpy is catagorical nominal value 
6. gender is catagorical nominal value 
7. age is numerical continious value 
8. tenure is categorical ordinal value 
9. balance is numerical continious value 
10. NumOfProducts is catagorical ordinal value 
11. HasCrCard is catagorical nominal value 
12. is active is catagorical nominal value 
13. Estimated salary is numerical continious value 
14. Exited is catagorical nominal  value

In [12]:
df['Gender'].value_counts()

Gender
Male      5457
Female    4543
Name: count, dtype: int64

In [15]:
# count occurrences of each Geography / IsActiveMember combination
df.groupby(['Geography', 'IsActiveMember']).size().reset_index(name='count')

  Geography  IsActiveMember  count
0    France               0   2423
1    France               1   2591
2   Germany               0   1261
3   Germany               1   1248
4     Spain               0   1165
5     Spain               1   1312

In [16]:
df['Exited'].value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

In [7]:
rows, cols = df.shape
print(f"Rows: {rows}\nColumns: {cols}")

Rows: 10000
Columns: 14

In [8]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64